apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::503763599459:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1B4RXKC61FR4D
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::503763599459:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-25T22:06:15Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1725"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 0b015f07-0b4f-4eb8-9942-a2550f5e4057
