apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::503763599459:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-SA28ZSG50L1L
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
	rolearn: arn:aws:iam::503763599459:role/UdacityFlaskDeployCBKubectlRole
	username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-22T15:10:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1578"
  uid: d4bb27c7-6ac1-4686-90fb-8b256c792346
